### PR TITLE
Adding Zato to the list.

### PR DESCRIPTION
**Pull request by dsuch**
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

### CODE REVIEW

**Review by Rabenherz112 — COMMENTED** [review]
Hi, thanks for your contribution.

However, there are no tagged releases for this project. Our guidelines require that _Any software project you are adding was first released more than 4 months ago._ We encourage you to create a release now and/or a simple [changelog](https://keepachangelog.com/en/1.1.0/) that will help users keep track of changes in the software (especially breaking changes or changes requiring configuration tweaks), and will allow administrators to install a known working, unchanging version (as opposed to always installing the latest development version).

Once this is done, the project may be resubmitted to awesome-selfhosted when the first release reaches the age of 4 months.

Thanks for understanding, and good luck with this project.

**Comment by dsuch** [comment]
Hi @Rabenherz112 and thank you for your comments.

- Zato is a mature platform, first released 10 years ago
- We use GitHub for code hosting and not much else, which is why there are no releases in the GitHub sense
- All the installation instructions and releases are here: https://zato.io/en/docs/3.2/admin/guide/install/index.html
- I understand your helpful hints about admins not wanting to install breaking changes but this is mature software, all such things have been worked out long ago and they do not apply here

I trust that this resolves your questions and you can now merge the commit.

Regards.

**Comment by nodiscc** [comment]
> there are no releases in the GitHub sense

Gtihub releases are not mandatory, however _some_ form of  stable release/changelog mechanism is, which does not appear to be the case here.

**Comment by dsuch** [comment]
hi @Rabenherz112 - we do not have a notion of non-stable releases.

When you go to the [installation page](https://zato.io/en/docs/3.2/admin/guide/install/index.html) you only ever get a stable release.

Then, any update to an already installed version is always stable and it is guaranteed never to break in backward-incompatible way.

Like I said, this is stable software, it has been around for 10 years, and we have worked out everything that is needed by its users as far as the installation and distribution mechanism go.

As to the changelog, it is not available publicly. This is not software for home use, people who use it need to have an account to access additional materials, which includes the changelog.

I hope that answers your questions?

I hope that

**Comment by Rabenherz112** [comment]
> As to the changelog, it is not available publicly. This is not software for home use, people who use it need to have an account to access additional materials, which includes the changelog.

I fail to see the correlation between targeting professionals with the software and the decision not to make the changelog public or at least having it locked behind an account. Prospective customers may want to verify the software's ongoing development and the nature of its updates beforehand.

Moreover, the [Docker hub image](https://hub.docker.com/r/zatosource/zato-3.2-quickstart/tags) (which is the only official installation method) lacks versioning as well and only offers the current "latest" tag, limiting any meaningful version control options. While I fully trust that your software is stable, users might still have some reasons to prefer specific versions.

I am personally still against adding this Software, which has no publicly available version control/release log.

**Comment by dsuch** [comment]
Is that the only obstacle that you see before Zato can be added to your list?

**Comment by nodiscc** [comment]
I agree with @Rabenherz112's assessment that the absence of a basic versioning/release system makes it unfit for inclusion in the current state.

> Is that the only obstacle that you see before Zato can be added to your list?

After a quick look, other criteria for inclusion seem to be fulfilled. 

> people who use it need to have an account to access additional materials

Which other restrictions are placed on the publicly available version?

> it is guaranteed never to break in backward-incompatible ways.

This is good, however a major problem with this approach is reproducibility (how am I supposed to keep staging and production environments on the same version of the code, for example? Blindly pull the latest version every 5 minutes? Given the industries targeted by the software I would expect more reliable QA possibilities).

Anyway this is a requirement for which I think we are not ready to make exceptions at the moment, even if the software looks mature. You can find a few precedents [here](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues?q=label%3A%22needs+to+mature%22+))

**Comment by dsuch** [comment]
I understand it @nodiscc - everything is clear.

**Pull request closed without merging**
