### PR TITLE
tools/hecat: do not warn about last update date for homepage, posio, bicimon, cubiks-2048

### PR DESCRIPTION
**Pull request by nodiscc**
- these projects are simple enough and have no external dependencies, so no maintenance is expected
- ref. https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/72
- ref. https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/242

### CODE REVIEW

**Comment by nodiscc** [comment]
As expected, no warning/error is raised for projects listed in `last_updated_skip`:

```
INFO:awesome_lint.py: Bicimon: skipping last update time check as per configuration (last_updated_skip) (-561 days, 7:11:27.185372)
INFO:awesome_lint.py: Cubiks-2048: skipping last update time check as per configuration (last_updated_skip) (-3430 days, 7:11:27.172919)
INFO:awesome_lint.py: Homepage by tomershvueli: skipping last update time check as per configuration (last_updated_skip) (-902 days, 7:11:27.152919)
INFO:awesome_lint.py: Posio: skipping last update time check as per configuration (last_updated_skip) (-744 days, 7:11:27.116016)
```

Note that the exclusions must be added to both `.hecat/awesome-lint.yml` (which runs for pull requests and commits on `master` but does not block the build) and `.hecat/awesome-lint-strict.yml` (which runs nightly and produces the badge  which indicates whether the list currently contains unmaintained projects.

**Review by kokomo123 — APPROVED** [review]
As long as they are simple in question, and they don't have any significant vulnerabilities (or will in the future), it looks fine to me!

**Review by KieranRobson — APPROVED** [review]
Nice and easy setup to contribute to!

**Review by Rabenherz112 — APPROVED** [review]
I largely agree with your selections and I'm pleased to see that we now have a means to exclude projects from the scan. However, I recall that your initial plan was not to permit permanent additions to a "whitelist."

> I don't think we want to permanently add a project to this ignore list, since it would be good to be reminded to revisit them after a while. So a simple ignore_list: ['project1', 'project2', 'writing' ] might not do the trick.

([Source](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/72#issuecomment-1688461538))

Is there any reason for this change, as I personally believe your idea of incorporating the 'until: 2024-08-22' feature was quite promising.

**Comment by KieranRobson** [comment]
As they are still in the list and the time is visible, Id say the current set up is fine.

**Comment by nodiscc** [comment]
>  I recall that your initial plan was not to permit permanent additions to a "whitelist." [...] your idea of incorporating the 'until: 2024-08-22' feature was quite promising.

I opted for a simpler implementation in the first time, which is also simpler to use. My concern with permanently adding projects to the ignore list, was that we might forget to check them again after some time. But the following points lead me to think it will not be a problem:
- The 4 projects I just added are static HTML/JS applications with no external dependencies, no server-side code, and will basically never require any kind of maintenance.
- Projects that match the ignore list are logged in hecat/github actions output, so they are not _completely_ silently ignored. I will probably check the logs linked from https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/1 and review these at least once a year, which is sufficient in my opinion. These projects' last update dates are still rendered in red on https://awesome-selfhosted.net/ which gives an additional hint.
- In cases where a project is actually in a _temporary_ grace period (e.g https://github.com/awesome-selfhosted/awesome-selfhosted/pull/4120), we can keep an issue or pull request open and tag it `on hold` (this particular one was closed during the migration to `awesome-selfhosted-data` but I will make a note to recheck on 21 November).

**Pull request merged**
