### PR TITLE
➕ Add the new `websurfx` project under search engine category

### LINKED ISSUE #127: Add `Websurfx`
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
# software name
name: "Websurfx"
# URL of the software project's homepage
website_url: "https://github.com/neon-mmd/websurfx"
# URL where the full source code of the program can be downloaded
source_code_url: "https://github.com/neon-mmd/websurfx"
# description of what the software does, shorter than 250 characters, sentence case
description: "Aggregate results from other search engines (metasearch engine) without ads while keeping privacy and security in mind. It is extremely fast and provides a high level of customization (alternative to SearX)."
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - AGPL-3.0
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - Rust
  - Docker
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - Search Engines
# (optional, yes/no, default no) whether the software depends on a third-party service outside the user's control
depends_3rdparty: yes
# (optional) link to an interactive demo of the software
demo_url: ""
# (optional) link to a list of clients/addons/plugins/apps/bots... for the software
related_software_url: ""
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.

### PR DESCRIPTION
**Pull request by neon-mmd**
## Contributing Checklist

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.

## Related Issues

Closes #127

### CODE REVIEW

**Review by KieranRobson — APPROVED** [review]
Looks good to me

One quick addition is I would add 
`Closes #127' above `Thanks for taking the time to suggest an addition to awesome-selfhosted!` so that the issues are linked.

**Comment by neon-mmd** [comment]
> Looks good to me
> 
> One quick addition is I would add `Closes #127` above `Thanks for taking the time to suggest an addition to awesome-selfhosted!` so that the issues are linked.

Ok thanks :heart: for pointing that out I just forgot about I am really sorry for that. But I will make the change right away :rocket: :slightly_smiling_face: .

**Comment by KieranRobson** [comment]
I have already approved!

**Comment by neon-mmd** [comment]
> I have already approved!

Ok, sorry, I didn't notice it. Also, do I have to merge the PR or is it waiting to be merged by the owner/other maintainers ??

**Comment by KieranRobson** [comment]
I am just a collaborator with triage perms, the maintainer is nodiscc, they have to review for it to be merged.

**Review by nodiscc — APPROVED** [review]

**Pull request merged**
