### PR TITLE
Add Manufacturing tag

### PR DESCRIPTION
**Pull request by hasecilu**
New category to allocate Octoprint & more.

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [X] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [X] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [X] Comments and unused optional fields have been removed.
- [X] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [X] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [X] Any software project you are adding to the list is actively maintained.
- [X] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.
- [X] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [X] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

### CODE REVIEW

**Comment by nodiscc** [comment]
Should be merged alongside https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/233 https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/236 https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/235 if/when these PRs are approved.

**Comment by KieranRobson** [comment]
Its a neat category to add and fosters other software. I can check the Misc section in the next couple of days to see if any would be a good fit for this tag,

**Comment by nodiscc** [comment]
> I can check the Misc section in the next couple of days to see if any would be a good fit for this tag,

It would be nice. I gave it a quick look and could only find https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/vandam.yml

**Comment by nodiscc** [comment]
(Disregard failing checks, I will merge this and related PRs together next week)

**Comment by hasecilu** [comment]
There is another program called CNCjs (https://cnc.js.org/) that I also want to add.

It's a web-based interface for CNC milling controller, very popular among makers with small CNC routers, lasers and very few 3D printers (since there are more specialized programs).

The thing is this kind of CNCs are very similar to 3D printers, the question is: should I add it to Misc or should be fine here on `3D printing`? Alternatively maybe a `Maker lab stuff`-like category?

**Comment by KieranRobson** [comment]
> https://github.com/cncjs/cncjs/ 
Source code for above

We could combine them to a `manufacture` category and then maybe an enterprise manufacturing if it came to it. Or `3D Printing and CNC` as a category.

**Comment by hasecilu** [comment]
I like `3D Printing and CNC`

**Comment by nodiscc** [comment]
> I like 3D Printing and CNC

I also like it, but `Manufacturing` could be a more sensible choice, since it would allow grouping 3D printer control software, CNC control software, PCB design software and more under a wider category.

I suggest renaming the file to `tags/manufacturing.yml` and changing the contents to

```yml
name: Manufacturing
description: "Software to manage [3D printers](https://en.wikipedia.org/wiki/3D_printing), [CNC machines](https://en.wikipedia.org/wiki/Numerical_control) and other physical manufacturing tools."
```

**Comment by KieranRobson** [comment]
> under a wider category.

This is important due to the low amount of available software available (That I have seen anyway). 

#233 / #235 / #236 / #239 / #244 will need their tags changed too to comply with the `Manufacturing` tag. I will change #239 shortly

**Comment by hasecilu** [comment]
> I also like it, but `Manufacturing` could be a more sensible choice, since it would allow grouping 3D printer control software, CNC control software, PCB design software and more under a wider category.

I agree on this, most of sotfware in this categories are usually for desktop, btw speaking of PCB design recently appeared [Ki-365](https://gitlab.com/ki365/ki-365) as an alternative to Altium 365 for collaborating electronics development, still an early phase though but could be a nice resource in the future.

> I suggest renaming the file to tags/manufacturing.yml and changing the contents to

Done

**Review by nodiscc — APPROVED** [review]

**Comment by nodiscc** [comment]
Rebased, squashed and merged in https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/268. Thanks

**Pull request closed without merging**
