### PR TITLE
Remove depends_3rdparty for Flyimg project

### PR DESCRIPTION
**Pull request by sadok-f**
Remove depends_3rdparty for Flyimg project to remove the flag ⚠ Anti-features

### CODE REVIEW

**Comment by kokomo123** [comment]
Uhh, you didn't actually remove the depends_3rdparty line for flyimg project, and can you give a description as to why you are removing it's dependency as it doesn't depend on 3rd partys, or..?

**Comment by nodiscc** [comment]
Hi, your commit is empty: https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/356/commits/c6d391bc45857f3939e7f55f6d3d3ae407645e6d

There is something strange going on: https://awesome-selfhosted.net/#flyimg is marked with `⚠ Anti features`, however https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/flyimg.yml#L11 states `depends_3rdparty: no`, so the Anti-features label shouldn't be there in the first.

I'll investigate

**Comment by sadok-f** [comment]
Sorry, I'm updating my PR to remove the depends_3rdparty option, it seems when setting the option to `no` it shows the flag ⚠ Anti-features

**Comment by nodiscc** [comment]
> it seems when setting the option to no it shows the flag ⚠ Anti-features

Yes it seems like so. This is a bug, I'll look into it.

Keeping this open since removing `depends_3rdparty: no` is also correct (it's the default value, at least in theory). Thanks

**Comment by nodiscc** [comment]
Fixed in https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/365

https://awesome-selfhosted.net/#flyimg

Thanks again

**Comment by sadok-f** [comment]
Great, thank you 👍

**Pull request closed without merging**
