### PR TITLE
platforms: Add RPM

### PR DESCRIPTION
**Pull request by KieranRobson**
Related to #117
Adds the rpm package manager suggested in https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/117#pullrequestreview-1619237527

I haven't gone through them yet however created, so others can contribute!

### CODE REVIEW

**Comment by nodiscc** [comment]
I don't think it brings much value to add the platform, without linking at least a few projects to it.

This should be worked on by people who use redhat derivatives (with the recent [demise of CentOS](https://arstechnica.com/gadgets/2020/12/centos-linux-is-gone-but-its-refugees-have-alternatives/), and now [RedHat putting GPL-licensed code behind a paywall](https://sfconservancy.org/blog/2023/jun/23/rhel-gpl-analysis/), I expect their numbers to shrink), and are interested in having this package format listed as a `platform`.

I'm not sure how this information can be gathered, I would check which packages are available for modern RH derivatives (AlmaLinux, Rocky Linux) at https://repology.org/

Personally I will keep enriching the `deb` platform I added in https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/117, but I don't think it makes sense to add `RPM` without anybody committing to maintain it over time.

**Comment by KieranRobson** [comment]
@kokomo123 @Rabenherz112 Do you guys use RPM? 

I don't mind working through some of the projects and adding some if it will help those who use RPM.

**Comment by Rabenherz112** [comment]
I'm sorry to disappoint you, but I exclusively use Debian and Windows in my infrastructure.

> I'm not sure how this information can be gathered, I would check which packages are available for modern RH derivatives (AlmaLinux, Rocky Linux) at https://repology.org/

This website is really helpful; however, for many projects, you don't need to go through the trouble of checking package availability with an external website because they usually include this information in their installation instructions. For instance, I came across [Miniflux](https://miniflux.app/docs/installation.html) while working on the [Language Tags Update](https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3976) (current progress can be found [here](https://github.com/awesome-selfhosted/awesome-selfhosted-data/compare/master...Rabenherz112:awesome-selfhosted-data:en-languages3)) which Lists all available packages really well.

**Comment by kokomo123** [comment]
I also have to disappoint you, Kieran. I use debian/arch linux/windows primarily so you could like nodiscc mentioned, put stuff for Alma or Rocky but that's all I can say. Thank you for all that you do for this list, and someone out there will appreciate this contribution and me too 👍🏻

**Comment by nodiscc** [comment]
Closing as per the comments above, feel free to resume working on this by tagging at least 5-10 entries with the `RPM` platform.

**Pull request closed without merging**
