### PR TITLE
Add mataroa blogging platform

### PR DESCRIPTION
**Pull request by sirodoht**
Mataroa is a minimal blogging platform.

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.

### CODE REVIEW

**Comment by KieranRobson** [comment]
I'd recommend cleaning up the deployment details to as much detail as the development section so people who skim through the README to the deployment section do not miss other ways to deploy.

**Comment by sirodoht** [comment]
Hi @KieranRobson!

There are detailed documents on deploying, namely:

* https://github.com/mataroa-blog/mataroa/blob/main/docs/deployment.md
* https://github.com/mataroa-blog/mataroa/blob/main/docs/server-playbook.md

I decided not to include all deployment steps on the README as they are too many, more than the development ones.

I did just make a change to include links to all relevant documents in the deployment section:

https://github.com/mataroa-blog/mataroa?tab=readme-ov-file#deployment

Finally, I'm not 100% sure I understood what you meant in your message. Please let me know if I misunderstood or if you think a clarification is needed!

**Comment by KieranRobson** [comment]
> I did just make a change to include links to all relevant documents in the deployment section:

This is a great addition and helps clean it up!

**Review by KieranRobson — APPROVED** [review]
This looks good to me!

**Review by nodiscc — COMMENTED** [review]
>  Any software project you are adding was first released more than 4 months ago.

Any plans to tag a stable release once in a while, so that users are not forced to run the latest development/unstable version?

**Comment by sirodoht** [comment]
@nodiscc hmm, interesting. I consider the latest `main` to always be stable (as it's the one running live at https://mataroa.blog/) but it might be interesting to have another more readable signifier of feature development and bug fixes. I've just released v1.0!

**Comment by nodiscc** [comment]
> I consider the latest main to always be stable

I didn't mean to imply that it is "unstable" in the sense "broken" (working on feature branches and good testing can help ensure the master branch stays bug-free), but in the sense "ever-changing". Many admins will want to choose when to upgrade the application, and take some time to read release notes, especially if there are breaking changes that require adapting the configuration for example.

I suggest creating a new release when either:
- a good batch of new features has been implemented and tested for some time
- an important bugfix has been made

And using release notes or changelog file to notify users of important changes. Good examples can be found here [[1]](https://github.com/go-gitea/gitea/releases/) [[2]](https://github.com/nodiscc/xsrv/blob/master/CHANGELOG.md)

Approving anyway since this software appears to have been running in production since a long time, despite the absence of stable releases.

**Review by nodiscc — APPROVED** [review]

**Comment by sirodoht** [comment]
> I suggest creating a new release when either:
>
>   * a good batch of new features has been implemented and tested for some time
>   * an important bugfix has been made
>
> And using release notes or changelog file to notify users of important changes.

Of course, that's reasonable!

Thanks!

**Comment by sirodoht** [comment]
Should I execute any further actions for this to get merged?

**Comment by KieranRobson** [comment]
Hi there,

Merges usually happen ~1 week after approval to allow for further comments if need be.

**Pull request merged**
