### PR TITLE
Add Stalwart Mail Server to Communication - Email - Complete Solutions

### PR DESCRIPTION
**Pull request by mdecimus**
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

### CODE REVIEW

**Comment by KieranRobson** [comment]
https://github.com/stalwartlabs/mail-server/releases/tag/v0.3.0

First release was on 16/06/23

Let's revisit on 16/11/23

**Comment by mdecimus** [comment]
@KieranRobson This is single binary combining Stalwart SMTP and JMAP servers which are already listed on the awesome-selfhosted repository. The first release is from [September 2022](https://github.com/stalwartlabs/jmap-server/releases/tag/v0.1.0).

**Comment by nodiscc** [comment]
> Merged the stalwart-jmap, stalwart-imap and stalwart-smtp repositories into stalwart-mail

In this case, the old https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/stalwart-jmap.yml and https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/stalwart-smtp.yml should be removed as stalwart-mail-server replaces individual components releases.

**Comment by mdecimus** [comment]
@nodiscc Stalwart SMTP and Stalwart JMAP are also available as standalone products.

**Comment by nodiscc** [comment]
In that case I suggest adding https://github.com/stalwartlabs/imap-server to the list first (we already list the JMAP and SMTP components, but the IMAP component is missing), then waiting until the first release of the integrated solution https://github.com/stalwartlabs/mail-server reaches 4 months (2023/11/16), as intended. This qualifies as a separate project with its own requirements, installation method, etc.

**Comment by mdecimus** [comment]
Sure, will do that. Should I close this PR and re-create it on 2023/11/26?

**Comment by nodiscc** [comment]
> Should I close this PR

No need, we can leave it open and come back to it in 3 weeks

**Review by nodiscc — APPROVED** [review]

**Comment by mdecimus** [comment]
Thank you!

**Pull request merged**
