### PR TITLE
Add: not-th.re

### PR DESCRIPTION
**Pull request by scolastico**
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

### CODE REVIEW

**Comment by nodiscc** [comment]
Hi, https://gitlab.com/not-three/main returns a 404 error, and https://github.com/not-three/main only has 7 commits, the first one from March 11.

>  Any software project you are adding was first released more than 4 months ago.

Feel free to reopen when this reaches the 4 months threshold.

**Comment by scolastico** [comment]
@nodiscc This wasnt even opend, this was a draft?!

**Comment by scolastico** [comment]
btw i knew it will not be accepted thats the reason it was a draft:
image

**Comment by nodiscc** [comment]
Sure, but I'd rather not keep a PR open for 4 months.
Feel free to reopen when this reaches the 4 months threshold, or a few weeks/days before.

**Comment by scolastico** [comment]
Yeah but that pr wasnt even opend, nevermind

**Pull request closed without merging**
