### PR TITLE
Add Exatorrent

### LINKED ISSUE #348: Add Exatorrent project is still alive and development is slow but satble
```yaml
# software name
name: exatorrent
# URL of the software project's homepage
website_url: https://github.com/varbhat/exatorrent
# URL where the full source code of the program can be downloaded
source_code_url: https://github.com/varbhat/exatorrent
# description of what the software does, shorter than 250 characters, sentence case
description: Easy to Use Torrent Client. Can be hosted in Cloud. Files can be streamed in Browser/Media Player. Files also are preview inside!
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - [GPL-v3](https://github.com/varbhat/exatorrent/blob/main/LICENSE)
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - Go
  - Svelte
  - TypeScript
  - JavaScript
  - Nodejs
  - Unix (for development is exclusive)
  - Cross platform
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - [go](https://github.com/topics/go)
  - [golang](https://github.com/topics/golang) 
  - [torrent](https://github.com/topics/torrent)
  - [cloud](https://github.com/topics/cloud)
  - [bittorrent](https://github.com/topics/bittorrent) 
  - [bittorrent-client](https://github.com/topics/bittorrent-client)
  - [bittorrent-client-gui](https://github.com/topics/qbittorrent)
  - [self-hosted](https://github.com/topics/self-hosted)
  - [gui](https://github.com/topics/gui)
  - [web](https://github.com/topics/web)
# (optional, yes/no, default no) whether the software depends on a third-party service outside the user's control
depends_3rdparty: no
# (optional) link to an interactive demo of the software
# demo_url: "https://my.awesome.softwar.e/demo"
# (optional) link to a list of clients/addons/plugins/apps/bots... for the software
# related_software_url: "https://my.awesome.softwar.e/apps"
```

- [x] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [ ] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.

### notes

Exatorrent was archived due mistakes and plans that now were stabilized, its under development but not so active, is focused on stability

### PR DESCRIPTION
**Pull request by Ki-er**
Closes #348
Install docs: https://github.com/varbhat/exatorrent/blob/main/docs/build.md

No official github releases however commits going back 4 months - https://github.com/varbhat/exatorrent/commit/cef2cc264ce0c03dbae3f5ba50a3b613905425b7

----

Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

### CODE REVIEW

**Comment by kokomo123** [comment]
Should we ask the devs for a stable release tag, or would a docker container be fine enough for a "stable release"

**Comment by kokomo123** [comment]
Thank you for asking 👍🏻

**Comment by Ki-er** [comment]
On my laptop I couldn't find the release but it seems there was releases https://github.com/varbhat/exatorrent/releases/tag/v0.1.2 a couple years ago.

As its 2 years, it's irrelevant to this pr but hopefully they are open to creating a new 1.0 release

**Comment by nodiscc** [comment]
> it seems there was releases a couple years ago.

Correct, it seems the `Releases` link is just not displayed on the project's page, but releases do exist: https://github.com/varbhat/exatorrent/releases

> As its 2 years, it's irrelevant to this pr

2 years without releases is concerning yes, and the releases page states:

>Releases of exatorrent is retired. Please use [Packages](https://github.com/varbhat/exatorrent/pkgs/container/exatorrent) instead.

But this link leads to a 404 page. Another link in the README states

> [Github Actions](https://github.com/features/actions) is used to build and publish [Docker Images](https://ghcr.io/varbhat/exatorrent) of exatorrent.

But https://github.com/users/varbhat/packages/container/package/exatorrent shows the latest image being pushed 9 months ago. So it seems their CI is not working anymore, and the image installation instructions refer to is 9 months old. So I'd say this we should at least wait for this to be fixed, before adding exatorrent to the list.

**Pull request closed without merging**
