### PR TITLE
Add OpenTrashmail

### PR DESCRIPTION
**Pull request by geek-at**
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

### CODE REVIEW

**Comment by nodiscc** [comment]
>  Any software project you are adding was first released more than 4 months ago.

This implies that stable releases are made available (either as git tags, or as changelog entries or any other mechanism). Currently there are no releases at https://github.com/HaschekSolutions/opentrashmail/releases, no changelog, and the documentation seems to imply that users should always install the latest development version.

I suggest creating a 1.0.0 tag for the current revision, and waiting it to reach 4 months before resubmitting this.

Thanks

**Comment by geek-at** [comment]
It's a rolling release with the latest version is the current commit in the `master` branch, which makes sense for projects of that scale (as do many other programs in the selfhosted list).

Over 100k docker pulls and a code base first released in 2019 should prove its maturity in my opinion.

**Comment by nodiscc** [comment]
Thanks, however currently we have no process in place to make exceptions to this rule.

A simple changelog would be beneficial (how would you warn users about breaking changes like [this](https://github.com/HaschekSolutions/opentrashmail/pull/56) otherwise?). A simple `git tag` would allow your users to pin a particular version without worrying about new commits breaking their workflow. It also provides a mechanism to notify users of urgent upgrades (security or otherwise).

> code base first released in 2019 should prove its maturity

It seems well done and a welcome addition, I'm looking for something similar since https://github.com/sj26/mailcatcher/ went unmaintained (actually maintenance seems to have resumed, so I'll take another look). As you can see many projects run by a single person *do* perform stable releases and maintain a [basic changelog](https://keepachangelog.com/en/1.1.0/). This is one of the only few "quality" requirements we have (see https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3880 for history, it's also one of the basic requirements from https://www.bestpractices.dev/en)

> Over 100k docker pulls

Irrelevant, my broken CI pipelines pull that in a week ;)

> as do many other programs in the selfhosted list

We're actively trying to prevent addition of such programs since the creation of this rule.

Why not create a 1.0.0 tag/release now since the software is working?

**Comment by geek-at** [comment]
You know, this actually makes a lot of sense to me.  Thanks for explaining!

I have updated the CI to include versions that are also referenced now in the docs and dockerhub/github repo.

Not only have I added this to opentrashmail but also to another program of mine that's already in your list: PictShare

**Review by nodiscc — CHANGES_REQUESTED** [review]
Great news. Considering this project has been maintained for quite some time, and a stable release/git tag/OCI image tag has been created, I would approve the addition once the remaining points are addressed

- `ERROR:awesome_lint.py: OpenTrashmail: description does not end with a dot`
- please remove comments (`#...`) and optional fields (`depends_3rdparty: no`)

**Review by nodiscc — APPROVED** [review]

**Pull request merged**
