### PR TITLE
Remove IceHrm (unmaintained since February 2023)

### PR DESCRIPTION
**Pull request by Haliax**
The demo-link is dead and redirects to a sales page.

This PR removes the link to the demo.

### CODE REVIEW

**Comment by Ki-er** [comment]
I believe this should be removed entirely due to being abandoned, and their open source model seems to be iffy.

- The GH repo has no commits since February 
- https://icehrm.com/cloud-hosting-charges - Hides some features behind charges
- Github install instructions differ from https://icehrm.com/explore/docs/install-icehrm-on-linux/
- Issues seem to be ignored however they comment on Pro ones - https://github.com/gamonoid/icehrm/issues/349

@nodiscc What do you think?

**Comment by nodiscc** [comment]
I have no problem with paid tiers getting priority support, or extra features being reserved to paid tiers, except for security-related features (https://sso.tax/) and arbitrary/artificial restrictions on the number of users, which is the case for IceHRM (could arguably be a violation of Freedom 0 [[1]](https://en.wikipedia.org/wiki/Free_software) _The freedom to use the program for any purpose._). See https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3480 for a bit more context.

This said, this project is already flagged in https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/1 `WARNING:awesome_lint.py: IceHrm: last updated -260 days, 5:34:40.124845 ago, older than 186 days`, so removing it is a possibility.

@Haliax can you edit your pull request to remove IceHRM?

**Comment by Haliax** [comment]
Sure. We were just browsing and noticed the broken link. But I can also edit the PR to remove it fully!

**Comment by nodiscc** [comment]
> I can also edit the PR to remove it fully!

Sure, please do.

**Review by nodiscc — APPROVED** [review]

**Pull request merged**
