### PR TITLE
Add anytype to the list

### PR DESCRIPTION
**Pull request by charlotte-chiang**
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x ] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [ x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x ] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x ] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x ] Comments and unused optional fields have been removed.
- [x ] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [ x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [ x] Any software project you are adding to the list is actively maintained.
- [ x] Any software project you are adding was first released more than 4 months ago.
- [x ] Any software project you are adding has working installation instructions.
- [x ] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [ x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

### CODE REVIEW

**Comment by Rabenherz112** [comment]
Hey there, from my understanding, the repo/software you suggested only includes Applications for End User Devices, which are non-hostable.
> A list of Free Software network services and web applications which can be hosted on your own servers

This list, however, is only for software which can be selfhoted on a server. However, please feel free to let me know if I have overseen a variant which can be hosted on a server.

**Comment by charlotte-chiang** [comment]
Hey @Rabenherz112, I'd like to correct: Anytype consists of several architectural levels:

End User Device Application, as you mentioned in your comment: their code and latest builds are in repos `anytype-ts`,` anytype-swift`, and `anytype-kotlin`.

Infrastructure Side Nodes: their code and latest builds are in repos `any-sync-node`,` any-sync-filenode`, a`ny-sync-consensusnode`, `any-sync-coordinator`.

Also, there are tools to simplify self-hosting, such as `any-sync-dockercompose`, `puppet-anysync`, and `ansible-anysync`. Please let me know in case of any questions, thanks!

**Comment by charlotte-chiang** [comment]
Hi @Rabenherz112 @nodiscc, following up on the above - please let me know if I should open a new PR. 

-- 

Anytype consists of several architectural levels:

-End User Device Application, as you mentioned in your comment: their code and latest builds are in repos anytype-ts, anytype-swift, and anytype-kotlin.

-Infrastructure Side Nodes: their code and latest builds are in repos any-sync-node, any-sync-filenode, any-sync-consensusnode, any-sync-coordinator.

Also, there are tools to simplify self-hosting, such as any-sync-dockercompose, puppet-anysync, and ansible-anysync. Please let me know in case of any questions, thanks!

**Comment by Rabenherz112** [comment]
Hey, thanks for the follow-up. I reviewed all the repositories you've mentioned. From what I can understand, although the code for the server-side infrastructure is available in these repositories, none of them include a web application or any form of interface. Instead, they all necessitate the use of End User Device Applications. Consequently, this excludes the Project from being included in the list, since this list only features software that can be self-hosted and provides some form of web interface.

I realize that my previous decline reason might have been badly worded, leading to some confusion. Sorry for that.

After going through [the tutorial](https://tech.anytype.io/any-sync/overview?id=infrastructure) explaining how self-hosting work in Anytype, it seems you can only self-host the infrastructure required to store/sync/retrieve the data from various End-User Applications. Please feel free to resubmit the project once the software is capable of being hosted as a web application and doesn't rely on its [desktop](https://github.com/anyproto/anytype-ts), [ios](https://github.com/anyproto/anytype-swift), or [android](https://github.com/anyproto/anytype-kotlin) app.

**Comment by charlotte-chiang** [comment]
Thank you @Rabenherz112 for taking the effort to respond, and I apologise that we hadn't understood the requirement of the software being a web app before submitting Appreciate your time.

**Pull request closed without merging**
