### PR TITLE
Add Procaptcha

### PR DESCRIPTION
**Pull request by HughParry**
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

### CODE REVIEW

**Comment by kokomo123** [comment]
I'm not sure about this one, as it requires a site key, plus you aren't entirely "self-hosting" the captcha provider at all, rather you are self hosting the code to call to the captcha server. Thoughts @nodiscc, @Ki-er?

**Comment by HughParry** [comment]
Worth noting that the sitekey is registered in a smart contract (the code for all of this is open source). Any user could deploy their own smart contract, register their sitekey in it and run providers which validate code.

All of the code for the frontend + backend & everything to run the network is in our monorepo

**Comment by kokomo123** [comment]
Ahhh, okay. Well then it makes more sense when explained clearly. My presumption is it talks to the captcha server, validates that site key, issues an API token, etc.

**Comment by HughParry** [comment]
Yeah and this captcha server is just a series of nodes that anybody can run if they want. If you want to have a look at what they're doing you can have a look at packages/provider in the repo

Definitely some work to do on improving our README 😆

**Review by kokomo123 — APPROVED** [review]
LGTM then, thanks for the explaination and thanks for the contribution 👍🏻

**Comment by Rabenherz112** [comment]
Hey there, as far as I could see, doesn't the readme only discuss how to implement the captcha into the application but not how to actually set up the server itself?

**Comment by nodiscc** [comment]
Not self-hosted. This is a SaaS product that you can integrate in your own web aplications by embedding javascrpt from their site.
Feel free to repoen if my analysis is incorrect.

**Pull request closed without merging**
