### PR TITLE
Add Gallery Deluxe to photo and video galleries

### PR DESCRIPTION
**Pull request by ribtoks**
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.

### CODE REVIEW

**Review by KieranRobson — COMMENTED** [review]
I don't believe this is hostable, and is just a plugin for Hugo? I may be wrong @ribtoks could you clarify as there aren't any installation instructions.

**Comment by ribtoks** [comment]
@KieranRobson Hey.
So first of all, this is certainly hostable as I decided to contribute it to awesome-selfhosted after I went through all of these static galleries and only this one worked out of the box!

Now, regarding installation instructions:
- The `README.md` of this repository actually points to a [started pack](https://github.com/bep/gallerydeluxe_starter) that has instructions how to start (you fork/mirror the repo and take it from there).
- This project generates a static website. "Installation instructions" are sort of not applicable for static website as you can "install" it wherever you want - hosting instructions will be different for CloudFlare, GitHub Pages etc. etc.

I hope it makes sense.

**Comment by nodiscc** [comment]
Hi @ribtoks 
We explicitly don't list static site generators. Please submit this at https://www.staticgen.com/ or https://staticsitegenerators.net/
Thanks

**Comment by ribtoks** [comment]
You do list them
- [Fussel](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/fussel.yml) - standalone in Python
- [Photo Stream](https://github.com/waschinski/photo-stream) - plugin for Jekyll
 
Gallery Deluxe is the same as them, but in Go and for Hugo.

**Comment by nodiscc** [comment]
Thanks for the heads-up. After reviewing Fussel and Photo Stream again, I think they actually fit in the `Static Site Generators` section, even though they are oriented towards picture galleries.

I will remove them, and suggest resubmitting them to one of the sites listed above (it's quite [easy](https://github.com/bevry/staticsitegenerators-list/pull/449/files) to do).

I also think the `Static Site Generators` and `Photo and Video Galleries` tags (and maybe `Content Management Systems (CMS)
`) should be marked as related to each other for better discoverability, I will send the necessary patch.

**Pull request closed without merging**
