### PR TITLE
Added tau.yml

### PR DESCRIPTION
**Pull request by samyfodil**
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [X] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [X] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [X] Comments and unused optional fields have been removed.
- [X] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [X] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [X] Any software project you are adding to the list is actively maintained.
- [X] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.
- [X] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

### CODE REVIEW

**Comment by nodiscc** [comment]
> Build Cloud Computing Platforms

I suggest submitting this to ~~https://github.com/awesome-foss/awesome-sysadmin?tab=readme-ov-file#cloud-computing~~ https://landscape.cncf.io/?group=projects-and-products&view-mode=card#app-definition-and-development--application-definition-image-build instead

> This is a list of [Free](https://en.wikipedia.org/wiki/Free_software) Software [network services](https://en.wikipedia.org/wiki/Network_service) and [web applications](https://en.wikipedia.org/wiki/Web_application) which can be hosted on your own server(s).

We focus on end-user applications

**Comment by samyfodil** [comment]
@nodiscc this project is the same as openFaaS which is in the list. Can you explain your logic?

**Comment by nodiscc** [comment]
Hi @samyfodil, this bring up the same problem/unclear distinction as the one mentioned in https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/462.

Basically, software that fits the one of the following criteria does not qualify:
1. requires you to write application code before producing a working end-user application (libraries, SDKs, ...)
2. acts as a platform for to build and deploy arbitrary applications (PaaS, "serverless"...)

OpenFaaS and others were added a while ago (2018, https://github.com/awesome-selfhosted/awesome-selfhosted/pull/1339), but the _FaaS and Serverless_ section has since grown to a mish-mash of unrelated software and this has become a concern (see for yourself: https://awesome-selfhosted.net/tags/software-development---faas--serverless.html, PaaS, firebase-like services, FaaS...), especially as the biggest challenge is to keep the list readable and with a clear scope.

I now _strongly_ feel that most of these tools should be moved to https://github.com/awesome-foss/awesome-sysadmin (maybe in a new section) if we want to keep our focus on... network services and web applications for the end-user.

As I wrote in #462 , the unwritten guideline about 1./2. not being in scope needs to be refined and written down.

I'm reopening this, but we should definitely move this section to awesome-sysadmin in the near future (and link to it from here)

**Comment by samyfodil** [comment]
@nodiscc I understand the concern. Still compare to many in the category, tau fits the definition of serverless.

**Comment by nodiscc** [comment]
Hi @samyfodil, https://awesome-selfhosted.net/tags/software-development---faas--serverless.html now redirects to https://github.com/awesome-foss/awesome-sysadmin#paas. I added Tau there.

Thanks for your patience.

**Pull request closed without merging**
