### PR TITLE
Add bitmagnet

### PR DESCRIPTION
**Pull request by mgdigital**
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

### CODE REVIEW

**Comment by nodiscc** [comment]
https://bitmagnet.io/:

> This software is currently in alpha. It is ready to preview some interesting and unique features, but there will likely be bugs, as well as API and database schema changes before the (currently theoretical) 1.0 release.

Given this information, do you think we should include it in the list right now? The software looks good - I'm actually subscribed to the releases RSS feed to be notified when 1.0 is released - and we have no strict guidelines about excluding beta/alpha software, and it's also good that this information is clearly visible on the homepage. @mgdigital would you consider it relatively stable and "production-ready", or are there major issues you would like to address before 1.0? Is there a roadmap to the first "production-ready" release?

**Comment by mgdigital** [comment]
Hi @nodiscc, I feel the project is now ready for me to start doing some active promotion - having done zero promotion since my Lemmy post announcing the first alpha release back in October.

The notice you quoted hasn't been updated since then. Though the software has become a lot more stable in that time, I don't think it's ready to remove or reword the notice yet. In terms of "production ready" it depends what this means... 

I've had enough feedback now that I'm happy the app is running stably for most users. There has been a lot of work to improve performance, which is now very acceptable even after indexing tens of millions of torrents. I don't see any major issues that should stop it being included, and I think the audience of Awesome Selfhosted are exactly the users who understand the implications of beta software and accept this. Perhaps it would be appropriate to have an "Early development" badge for such projects. Of course there will still be minor bugs and missing features, and those who choose to install now might have a little work to bring their installation along the upgrade path as it gets more mature - for example removing the dependency on Redis and moving the job queue to the Postgres DB, which I'm working on at the moment. Providing alternative and simpler installation methods is also a priority, but I think the audience here is comfortable with using Docker or building things on the command line.

I agree there should be a roadmap to 1.0 (there is a roadmap of sorts on the website), I still need to decide exactly what does and doesn't need to be a part of 1.0!

**Comment by nodiscc** [comment]
> In terms of "production ready" it depends what this means...

No unaddressed known security or data loss issues, no major/crippling bugs that make the software unusable. Generally reliable.

> work to improve performance, which is now very acceptable

Performance is not a requirement, as it is hard to quantify objectively (joules/torrents indexed? :thinking: ). It's still good that you are working on this.

> Perhaps it would be appropriate to have an "Early development" badge for such projects

This is a lot of work to maintain manually, as we can't know when this is the case, and _when to remove the badge_ (we can't rely on the latest release tag either, some `v0.x` projects are actually very reliable).

The closest thing we have are `Anti-features` inspired from [F-Droid](https://f-droid.org/docs/Anti-Features/) (currently only [one](https://awesome-selfhosted.net/#anti-features) is implemented), which doesn't have an `Early development` category either.

We already have a requirement of 4 months since first release before a project can qualify, so bitmagnet qualifies.

Given all this, your word is good enough.

> those who choose to install now might have a little work to bring their installation along the upgrade path as it gets more mature

As I would expect, as it is clearly stated on the homepage/README.

> for example removing the dependency on Redis and moving the job queue to the Postgres DB, which I'm working on at the moment

Personally I'll wait for this breaking change to show up in my RSS feeds before trying out bitmagnet

What do you think about keeping this PR on hold until this _last_ difficult step in the upgrade path is removed?

Thanks and keep up the good work.

**Comment by mgdigital** [comment]
> no major/crippling bugs that make the software unusable ... Performance is not a requirement

In this case, prior to v0.5.0, performance might have been seen as a bug, because the app would become cripplingly slow after indexing millions of torrents - so this release was a big step forward.

> What do you think about keeping this PR on hold until this last difficult step in the upgrade path is removed?

I'm happy with that - it'll give me motivation to get this bit finished, shouldn't be too long anyway.

Cheers!

**Review by nodiscc — APPROVED** [review]
:ok_hand:

**Pull request merged**
