### PR TITLE
platforms: add `deb` platform for software that can be installed trough .deb packages

### PR DESCRIPTION
**Pull request by nodiscc**
- this platform may be added to software that is installable through .deb packages/repositories (either official Debian repositories, or repositories/.deb packages provided by project maintainers)
- related https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/71
- added the platform to a few items (not exhaustive)

### CODE REVIEW

**Review by KieranRobson — APPROVED** [review]

**Review by kokomo123 — APPROVED** [review]
This does make sense, as it's easier to install deb packages. 👍🏻 💯

**Review by Rabenherz112 — APPROVED** [review]
I think it definitely makes sense to list package installations as an installation method. Does it also make sense to consider adding support for other popular package formats, such as RPM (Redhat, Fedora, CentOS, SUSE), if applicable?

**Comment by kokomo123** [comment]
> I think it definitely makes sense to list package installations as an installation method. Does it also make sense to consider adding support for other popular package formats, such as `RPM` (Redhat, Fedora, CentOS, SUSE), if applicable?

I also agree, though that'd be a lot of editing files, I suspect it could be done. I approved this knowing that this could potentially lead to other packaging support, perhaps?

**Comment by nodiscc** [comment]
> Does it also make sense to consider adding support for other popular package formats, such as RPM

I think it does

> though that'd be a lot of editing files

It's a collaborative list so people who are interested in this can put in the required work themselves :) I don't use RH-based distros, but I think RPM is popular enough to accept it as a valid language/platform tag.

**Pull request merged**
