### PR TITLE
Add `ytdl-sub`

### PR DESCRIPTION
**Pull request by jmbannon**
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [x] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [x] Comments and unused optional fields have been removed.
- [x] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
- [x] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

### CODE REVIEW

**Comment by nodiscc** [comment]
Hi, see https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3838

**Comment by jmbannon** [comment]
Ah I forgot that existed. FWIW there is a new docker image that offers a "gui" via code-server. That aside, I'd respectfully argue usage of ytdl-sub is equivalent to beets which is on the list

**Comment by nodiscc** [comment]
> usage of ytdl-sub is equivalent to beets which is on the list

ytdl-sub's "web interface" is a in-browser vscode instance which allows you to edit the config file and access the command line from a web browser (effectively the same as SSHing to the server, [screenshot](https://github.com/jmbannon/ytdl-sub#docker-installation)). If we started allowing this, any command-line program would qualify.

Beets' web interface is a web application + REST API (https://docs.beets.io/en/latest/plugins/web.html#run-the-server).

I don't think these can be compared.

**Comment by jmbannon** [comment]
Beets is aimed at running in the CLI. Its web app is an after-thought plugin that proclaims it's clunky and can't do much - probably not used by many if at all.

My argument is the list already contains CLI driven apps. Adding a filter that it has to have a 'REST-based web-gui' even if it's not part of the main application IMO defeats the purpose of what I imagine is the actual intent of that rule: usability/ease-of-use, which I think both ytdl-sub and beets have done well for CLI-based tools.

**Comment by nodiscc** [comment]
> the purpose of what I imagine is the actual intent of that rule: usability/ease-of-use

The purpose is actually to restrict the scope of the list, to prevent it from growing too much (number one usability issue, 1205 projects listed, we have to restrict what goes in there somehow, yes it's arbitrary and won't please everyone, especially if it's their own project being excluded). This has been debated *countless* times, and is no longer up to debate, sorry. X11-forwarding GIMP over SSH does not make GIMP "self-hosted", accessing `top` or `ytdl-sub` from a browser-based terminal emulator/IDE does not make these "self-hosted", syncing a .docx file using Nextcloud does not make MS Word "self-hosted"... at least in the context of this list. Please look for previous issues stating the exact same thing in https://github.com/awesome-selfhosted/awesome-selfhosted/issues/ (don't have a ready-made list at hand, sorry). Beets has a basic web interface and HTTP API which ytdl-sub does not have - period.

It's not a judgement on the quality of your software, which indeed looks good and easy to use.

The best I can suggest is adding `related_software_url: https://github.com/awesome-jellyfin/awesome-jellyfin` to https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/jellyfin.yml. This community-maintained list already shows ytdl-sub and many other tools/clients/plugins related to Jellyfin. This will show up on the list as a `Clients` link (the word _Clients_ is no longer accurate since it's now used more generally for lists of clients/plugins/mobile apps/companion scripts like yours, etc. we might change the wording someday)

You could find similar lists for Kodi/Plex/Emby, add ytdl-sub to these lists, and add them as `related_software_url` for these projects as well.

What do you think?

**Comment by jmbannon** [comment]
I still respectfully disagree with the sentiment of the guideline, but appreciate the explanation and suggestions. Thanks for the consideration and your work on maintaining this :slightly_smiling_face:

**Pull request closed without merging**
